POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "christopher_phillips",
  "password": "christy@123"
}

###
GET http://localhost:3000/states

Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjc5MTI1ODM5fQ.0Ov5tk0V-y-my83_caazn7UDtKwI4-Xsxq6ozOl1qX8
###
GET http://localhost:3000/states/:stateId/

Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjc5MTI1ODM5fQ.0Ov5tk0V-y-my83_caazn7UDtKwI4-Xsxq6ozOl1qX8
###
POST http://localhost:3000/districts/

Content-Type: application/json

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}

Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjc5MTI1ODM5fQ.0Ov5tk0V-y-my83_caazn7UDtKwI4-Xsxq6ozOl1qX8
###
GET http://localhost:3000/districts/:4/

Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjc5MTI1ODM5fQ.0Ov5tk0V-y-my83_caazn7UDtKwI4-Xsxq6ozOl1qX8
###
DELETE http://localhost:3000/districts/:4/

Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjc5MTI1ODM5fQ.0Ov5tk0V-y-my83_caazn7UDtKwI4-Xsxq6ozOl1qX8
###
PUT http://localhost:3000/districts/:5

Content-Type: application/json

{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}

Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjc5MTI1ODM5fQ.0Ov5tk0V-y-my83_caazn7UDtKwI4-Xsxq6ozOl1qX8
###
GET http://localhost:3000/states/:4/stats/

Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjc5MTI1ODM5fQ.0Ov5tk0V-y-my83_caazn7UDtKwI4-Xsxq6ozOl1qX8
